# Este workflow vai gerar um relatório de resultados de testes em HTML extra

name: Newman Tests
on: [push, pull_request]

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      # Faz o checkout do repositório
      - uses: actions/checkout@v3  # Atualizado para v3
      
      # Instala o Node no runner
      - name: Install Node
        uses: actions/setup-node@v3  # Atualizado para v3
        with: 
          node-version: '16.x'
    
      # Instala o Newman e o HTML extra reporter
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
          
      # Cria o diretório para os resultados dos testes
      - name: Make Directory for results
        run: mkdir -p testResults
        
      # Executa a coleção POSTMAN
      - name: Run API Tests
        run: newman run "Restful Booker BVT.postman_collection.json" -e Production.postman_environment.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html

      # Faz upload do conteúdo do diretório de resultados dos testes
      - name: Output the run Details
        uses: actions/upload-artifact@v3  # Atualizado para v3
        with: 
          name: RunReports
          path: testResults
